package net.chennj.remotectrl.common;

public enum Errno {

	NIO_SUCCESS,
	NIO_OVERSIZE_ERROR,
	NIO_READHEAD_ERROR,
	NIO_READBODY_ERROR,
	NIO_INVALIDFORMAT_ERROR,
	NIO_INVALIDTYPE_ERROR,
	NIO_LOSTLABEL_ERROR,
	NIO_CLIENTCLOSE_ERROR,
	NIO_PARSE_ERROR,
	NIO_SENDTARGET_ERROR,
	NIO_OTHER_ERROR
}
